<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>SubtitleCloudPlugin</AssemblyName>
    <RootNamespace>SubtitleCloudPlugin</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.8.11.0" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <EmbeddedResource Include="PluginPage.html" LogicalName="SubtitleCloudPlugin.PluginPage.html" />
    <EmbeddedResource Include="Dashboard.html" LogicalName="SubtitleCloudPlugin.Dashboard.html" />
    <EmbeddedResource Include="SubtitleCloudPage.js" LogicalName="SubtitleCloudPlugin.SubtitleCloudPage.js" />
    <EmbeddedResource Include="SubtitleCloudPlugin.js" LogicalName="SubtitleCloudPlugin.SubtitleCloudPlugin.js" />
  </ItemGroup>
</Project>
