<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>SubtitleCloudPlugin</AssemblyName>
    <RootNamespace>SubtitleCloudPlugin</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.8.11.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.8" />
    <EmbeddedResource Include="PluginPage.html" LogicalName="SubtitleCloudPlugin.PluginPage.html" />
    <EmbeddedResource Include="shortcuts.js" LogicalName="SubtitleCloudPlugin.shortcuts.js" />
  </ItemGroup>
</Project>
